apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      automountServiceAccountToken: false
      containers:
        - name: authentication
          image: rickwalking/authentication
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8080
          env:
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: sqlalchemy_database_uri
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: secret_key
            - name: SQLALCHEMY_TRACK_MODIFICATIONS
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: sqlalchemy_track_modifications
            - name: RABBIT_MQ_URL
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: rabbit_mq_url
            - name: RMQ_QUEUE
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: rmq_queue
            - name: RMQ_QUEUE_DURABLE
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: rmq_queue_durable
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: rabbitmq_host
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: rabbitmq_port
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: rabbitmq_user
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: rabbitmq_password
            - name: RABBITMQ_EXCHANGE_NAME
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: rabbitmq_exchange_name
            - name: RABBITMQ_QUEUE_NAME
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: rabbitmq_queue_name
            - name: RABBITMQ_ROUTING_KEY
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: rabbitmq_routing_key
            - name: RABBITMQ_HEARTBEAT
              valueFrom:
                secretKeyRef:
                  name: authentication-env
                  key: rabbitmq_heartbeat
