apiVersion: v1
kind: Service
metadata:
  name: authentication
  namespace: microservices
spec:
  selector:
    app: authentication
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: LoadBalancer
